### ISSUE TITLE
Need a better way of managing input, among other things

### ISSUE THREAD

**Issue by Derjyn** [segross/UnrealImGui#1]
This is really awesome, however it's a bit annoying having to work around input methods.  Exposing more functionality would be great- both in C++ and some blueprint nodes.  I'm able to toggle ImGui on with a key press, but after that I have to use the console to toggle the input off, then I can use my own key shortcut to toggle ImGui display.

What I'm doing is:
- Toggling a debug boolean with a key press
-  Checking if debug mode is on, and if so, draw ImGui
- _Trying_ to toggle debug boolean off, and hide ImGui (this is where things fall apart)

Wrapping up a lot of ImGui in easily accessible C++ and BP nodes would be awesome.  If I weren't wrapped up a dozen other projects, I'd probably tackle it myself :wink:

So, this is more of an issue plus feature request!  Again, this is awesome to see in UE and quite welcome.  A bit more polish and it would be amazing :gem:

**Comment by segross** [comment]
Hi @Derjyn. Thank you for your feedback and sorry that you had to wait this long. I was away from the project during the holiday, so I didn’t event notice this thread.

You are right that using console to switch input mode is not convenient. However, since I gave a higher priority to more ‘fundamental’ features over those usability ones and because of a general lack of time recently I kept postponing fixing it. But I can see how this can be a problem, so I will look at this.

On that note, could you please clarify a bit what exactly is your work-flow and issue, as I’m not fully sure what do you mean by toggling ImGui on and input off?

To give a better insight what is happing, this is an overview of the ImGui Module behaviour:
- For every world detected it creates a dedicated ImGui context and if that world has a view-port it attaches an ImGui Widget to it.
- Each ImGui Widget is always visible, so as soon as you start adding controls to the corresponding context they will show-up in the view-port. And of course, once you stop drawing controls then widget will become empty.
- By default ImGui Widgets are set-up to stay as ‘physically invisible’ as possible, that is to be visible to the user but invisible to hit tests and input in general. Enabling input mode reverses that situation and ImGui gets exclusive access to mouse and keyboard (with some exceptions to support console etc.).

One way to change input mode without opening the console would be to modify CVar like this:
if (auto* ImGuiInputEnabled = IConsoleManager::Get().FindConsoleVariable(TEXT("ImGui.InputEnabled")))
{
	ImGuiInputEnabled->ClearFlags(ECVF_SetByConsole);
	ImGuiInputEnabled->Set(InputMode); // where InputMode = 0, 1 or (ImGuiInputEnabled->GetInt() > 0 ? 0 : 1)
}
This should already work but I will add utility functions that can do that, so game code doesn’t need to depend on CVar name. Unless I’m missing a point, this should solve your problem.

This still leaves the burden (and power) of triggering input state outside of the module. I will need to investigate a possibility to additionally handle that state change inside of the module but so far I wasn’t 100% happy with any solution. What I ended up doing was to handle that from a custom view-port on the game side.

**Comment by segross** [comment]
I added an interface to modify from code console variables that control whether to enable ImGui Input Mode and show ImGui Demo. This can be used to easily switch state from code and for instance to use it in custom viewport etc. From my tests it seems to work as expected.

There is no blueprint equivalent right and the reason is that I didn’t yet establish what would be the best way to disable blueprints in non-development builds. I will change ImGui module setup in a way that it will be possible to completely strip down non-development builds from ImGui, but with blueprints it doesn’t seem to be that easy. So, quite possibly blueprint library might require a separate module(s).

**Comment by segross** [comment]
I believe that when I looked at the issue the first time I misunderstood the real problem here. June updates (from 5968c3ce and up) introduced a few improvements to input handling:
- There is an ImGui Input Handler class. It is not 'a true handler' but a class that defines rules how input should be handled, but in a limited scope it also allows to add own handling code.
- Default handler implementation consumes most of the keyboard events, with a few exceptions to allow console activation, stopping editor play session and switching ImGui input state.
- Console activation and stop play session keys are read from configuration, so they support custom project settings.
- Keyboard shortcut for switch ImGui input mode can and need to be defined in ImGui project settings.

It would be possible to add more rules and settings (like defining default behaviour for input consumption or providing a list of ignored key events etc.), but with already a few different solution in Unreal it is not always possible to provide a general solutions that works in all different cases. From that reason there is only a few basic rules and if that is not enough for particular project, then custom handler can be implemented and set in ImGui project settings.

I might revisit default implementation later but I think that with above changes it should be possible to customize input to own preferences.

Blueprint is a different topic. One problem that I had was that it was not possible or easy to define blueprint functions that would be removed in shipping builds (and since this is a debug tool that should be possible). This has been fixed in 4.17 or 4.18, if I remember right, but I still need to decide whether that should be in the same or separate module etc. Also while it would be easy enough to follow C++ patter and require begin/end nodes, in blueprint it would be better to have something like for-loop node. This is duly noted but I won't have time to look at this now.

Closing topic because I think that the title problem is now solved.
