### ISSUE TITLE
support of iOS/Android

### ISSUE THREAD

**Issue by gibyfred** [segross/UnrealImGui#16]
hello, 

I am  trying to use it and it works for UE4 Editor but when trying to run on my Android,
I have got assertion at the checkf in the file
     Plugins\ImGUI\Source\ImGui\Private\ImGuiInteroperability.cpp
inside the function GetKeyIndex().

It is called by the line below, which is inside the ctor of FUnrealToImGuiMapping
  KeyMap[ImGuiKey_PageDown] = GetKeyIndex(EKeys::PageDown);

Actually, is Android and/or iOS supported or, if not yet, do you have any plan?

Thank you for your time.
Giby

**Comment by segross** [comment]
Hey, the intention of course is that it supports all the platforms that can be supported by ImGui but I develop it on PC and problems like this may happen. I'll try to help but I don't really build for Android nor iOS so it will be hard fro me to test it on my own.

In short, this is clearly a wrong assertion and it needs to be removed. I think that in this case the best approach will be to map unsupported keys to 0 as for null, which means changing:
```C++
checkf(false, TEXT("Couldn't find a Key Code for key '%s'. Expecting that all keys should have a Key Code."), *Key.GetDisplayName().ToString());
return -1;
```
to:
```C++
return 0;
```
This will guarantee that ImGui key map is always initialized with unsupported keys mapped to 0. Actual input events with non-zero key codes (passed from system events), should never raise that flag in input state and therefore keep unsupported keys inactive.

If that works correctly then I will upload a change to the repository.

I wanted to revisit key mapping anyway as I know that there is some disparity between key codes passed with input events and those read from input manager. It would be possible to force the same mapping function or provide completely custom mapping altogether but as long as it works for a set of keys defined in ImGuiKey_ enum I try to use codes provided with input events as it means less indirections when handling input.

**Comment by segross** [comment]
I’m glad that it fixed this problem causing crash. I’ve committed that change to the main branch already.

When it comes to not supporting touch input, it makes sense given that I didn’t actually implement it ;) I was going to add that to this discussion but you bet me to it.

If you want to try to get it to work, I would start from SImGuiWidget and support it there. You may notice that it is using "input handler" but I would ignore it for now. I’ve added that handler to allow limited control from game code but I’m thinking about refactoring/replacing or dropping it.

Once you get touch event in widget, I think you will need to translate it to mouse input (as I don’t think that ImGui support touch input) and store it in InputState.

Unfortunately, I didn’t try using touch interface myself. I might check it, if UE has some sort of emulation mode that would allow me to test it.
 
Few things to keep in mind:
- I’m just refactoring widget and send first change probably today afternoon.
- Future of the "input handler" is not clear, so I wouldn’t mess with it for now.
- Handling touch input might require changing how input mode is evaluated and updated. If you have any problems with that I will try to help and maybe update that logic.
- I’m thinking about adding Remote ImGui that allows to connect to game from web client. I have it somewhere in my old repository but I will need to find it and clean. I try to keep plugin "remote-ready" (hence the input state rather than controlling ImGui IO directly) but I didn't make the final push to add it. Using remote could mitigate any input problems but I'm not sure whether this is something you are interested with. I personally use it this way in my work and prefer it even when I'm developing on PC, it just makes my game viewport clean while allowing me to draw big number of debug windows.

**Comment by gibyfred** [comment]
Thank you for the comments and suggestions!  Sorry for my late response.
