### ISSUE TITLE
Pass through unhandled mouse input to viewport

### ISSUE THREAD

**Issue by rokel** [segross/UnrealImGui#18]
Thanks for an awesome plugin.

Is there any way to pass through unhandled mouse events to the game viewport when input is enabled? Similar to the keyboard sharing, for when the mouse is not over an ImGui widget.

**Comment by segross** [comment]
Hey, thank you.

When it comes to passing mouse input… yes and no. I tried it and it didn’t work as I expected, so I left it unresolved, hoping that maybe one day I would revisit it.

It was a while ago and I don’t really use Slate that much, so correct me if I’m missing something, but from what I remember the issue was somehow connected with viewport not processing mouse input when mouse capture was held by a widget. And we need to capture mouse, if we want to process mouse input. I think that it worked fine when game was in menu but not when passing input to player controller.

Since that time I changed a bit how I take and release the input so I may try again, but it may be something more fundamental. Can you actually share mouse between Slate/UMG menu and player controller?

Arguably, handling input is not very flexible at the moment and I’m thinking about changing it to allow easier customisation.

May I ask what is your use case and why you need to pass mouse input?

I myself decided to separate debug from game input to avoid situations where interacting with debug UI would affect the game state. I want to keep that possibility but obviously other people may have different view on that. Also keep in mind that it is possible to bind a key to input toggle command, what makes switching relatively fast.

**Comment by rokel** [comment]
Fair enough. So my use case is to essentially use ImGui as a replacement for normal Slate widgets rather than just a debugging UI, as it suits my project much better (it's a data visualiser where lots of data changes every frame). I think combined viewport/widget input is possible if you set the input mode to accept Game and UI e.g.:

```cpp
  PC->SetInputMode(FInputModeGameAndUI());
  PC->bShowMouseCursor = true;
```

I suppose one solution might be to set `FImGuiModule::Get().GetProperties().SetInputEnabled(true);`  when the mouse enters an ImGUI window and disable it when it leaves. Do you have any suggestions on how I might hook into those events from user code to do that? It looks like SImGuiWidget wraps the whole ImGui canvas rather than individual windows so can't just use the SWidget OnMouseEnter/Leave methods...

**Comment by segross** [comment]
Ok, this is a bit different than I originally planned. But it is interesting and it would be good to better support it.

ImGui widget fills the whole viewport which usually amounts to some part of the canvas but you are right that it doesn’t wrap individual windows. It is one way to ensure that input can be fully blocked and it makes rendering easy.

I'm not sure how easy it would be to divide ImGui output between different widgets. I think that each command might correspond to a different window but I didn't check whether this is always true and whether this is something guaranteed. But I think that it would require a bit more management on the Slate side, though.

Alternatively, maybe it would be possible to modify a widget geometry in a way that it matches ImGui. This way you could use mouse enter/exit events to determine whether the mouse cursor is above ImGui window, while still having only one widget to manage. However, I don't use Slate that much and I don't know how easy it is, if at all.

Also, if you need an ImGui based mechanism, then it should be possible to either read it from ImGui IO or to add it to `FImGuiContextProxy` (see `FImGuiContextProxy::HasActiveItem`or `FImGuiContextProxy::GetMouseCursor` for reference).

Finally, I think that I did try setting input mode in a way that you suggested, but something didn't work. I don't remember what exactly, so I will need to test it again. An easy way to see how that works is to change `SImGuiWidget` mouse handlers to return unhandled responses. I will try it myself when I have a moment, but if you want to test how it works that is probably the quickest way.

**Comment by segross** [comment]
So, I’ve checked, and I think that I remember why mouse sharing didn’t work for me:
1) With the input mode enabled, other Slate widgets are occluded by ImGui Widget and don’t get the mouse enter events. This is fine if a clean input mode is what you want but obviously not so much if you want to share input.
2) With mouse cursor visible I need to keep button pressed to get player input.

The second point is the default behaviour in the engine, so I guess it is fine. The first point means that when using Slate UI then it works better with the clean input mode.

However, in case of mouse input you can actually get cursor coordinates and button states. So it might be possible to keep widget hit-invisible or to check ImGui whether to switch between hit-invisible and visible modes. If you are not using Slate UI, this might not even be a problem.

**Comment by segross** [comment]
I have pushed changes enabling shared mouse. It works in a way that depending whether mouse cursor is hovering ImGui widow or not, the widget is hit-test visible or invisible. When the widget is hit-test invisible, it only updates mouse position. Clicking outside of the ImGui window relinquish the whole input to the viewport.

There was also a bit of refactorization, so it should be easier to customise it, if necessary.
