### ISSUE TITLE
When mouse input sharing is turned on, the ImGui window may not receive focus.

### ISSUE THREAD

**Issue by UserKY** [segross/UnrealImGui#26]
Hello.

When mouse input sharing is turned on, clicking (or touching) the ImGui window may not receive the focus.
(It happened when playing the game while displaying the debug menu on ImGui.)

It occurs when the following procedure is performed.
1. Turn on mouse input sharing setting and start gameplay
1. Display the ImGui window (for example, use the ImGui.ToggleDemo command)
1. Turn on ImGui input (for example, use the ImGui.ToggleInput command)
1. Click the part that is not the ImGui window
1. Click the ImGui window

In 5, ImGui window does not receive focus.
I want to focus just by clicking on the ImGui window. Is there any way?

**Comment by segross** [comment]
I will try checking tomorrow to remind myself how that works but unfortunately, I think what you want is not easily achievable. As described here https://github.com/segross/UnrealImGui#sharing-input, mouse sharing is a bit different. Unconsumed keyboard and controller input can be easily shared but in case of the mouse input it allows game viewport to grab mouse capture from the ImGui. Taking it back would be possible, but it would defeat the whole purpose of sharing. One solution is to keep input as long as cursor is in inside of the area covered by ImGui widgets and release it after clicking outside of that area.

Once you know a specific use case and requirements, it is possible to modify `SImGuiWidget` behaviour but there is no one solution covering all cases. I would hope to make those modifications easier in a future, but there are no immediate plans for that right now.

In your case, you could try looking at `void SImGuiWidget::UpdateInputState()`. In particular, code between lines 439-448 in `SImGuiWidget.cpp` should be responsible for the behaviour that you don't like.

Out of curiosity, may I ask what is your use case? I'm asking because the original design was for debugging and for that I feel that sharing is undesirable. However, sometimes people use it for an application UI, and usually in those cases mentioned limitations show-up.

**Comment by UserKY** [comment]
Thank you for your reply.

I am using ImGui for debugging.
However, you may play the game while displaying ImGui.

I use it as follows.

![GamePlay](https://user-images.githubusercontent.com/48268474/76389965-d740db80-63af-11ea-92e9-4d505daacc42.png)

This is a scene of playing a game while displaying the ImGui window.
In this game, move the player with the ASDW key and rotate the camera by holding down the mouse button and dragging.

In this situation, you had to move the player to a specific location and then press the debug button (for example, the "Test!!" button).
At that time, I noticed that the buttons on ImGui did not respond.

**Comment by segross** [comment]
Yes, for debugging you have to re-enable ImGui input or never share it. In the case of the mouse input "sharing" = share cursor position + auto-release after clicking outside of the ImGui. I should probably update the readme file to make it cleaner. You may try modifying `SImGuiWidget.cpp` to see if you can get it working as you want it. Please share if you find a way, as I would gladly try to integrate it if it doesn't break other use cases.

Should we close this issue for now?

**Comment by UserKY** [comment]
I understand what "share" means. I want to change `SImGuiWidget.cpp` as necessary.

Thank you so much

**Comment by segross** [comment]
Sure, feel free to post an update, if you find a way to do it. Maybe there is a nicer solution to whatever I have found,  so I might update the widget.
