### ISSUE TITLE
4.25 issues - old style monolithic headers being used and deprecated plugin type being used

### ISSUE THREAD

**Issue by jerryeds** [segross/UnrealImGui#31]
Noticed that this is still using the old style monolithic headers. I have a change to remove the old style core.h, engine.h, slatecore.h and replace them with specific headers and/or forward declares if you are interested in the pull request.

**Comment by segross** [comment]
Thanks for that change list @jerryeds. I admit that I misunderstood your request. I was thinking about switching away from the explicitly included PCHs, which used to be a problem in some older engine versions and a reason why I didn't switch yet. But what you gave me makes a great sense of course. Why didn't I think about that? :) I somehow mentally combined removing PCH and fixing includes into one task.

In that change list, other than the ImGui.uplugin and ImGuiContextManager.h, ImGuiModuleManager.h with SImGuiLayout.h which should be already fixed by my last commit, the rest is fine. If you want, you can make a push request. And if not, I'll just copy stuff. It's a weekend anyway, so I can sit and fix it.

I'd like to change module type but I'm not sure how to best handle it. In my last company, we still used 4.22 at least in one project and now in another company we also use 4.22. So those are pretty much still in use.

**Comment by segross** [comment]
I cleaned up includes and removed usages of monolithic headers. I compiled that with bTreatAsEngineModule enabled (locally  for now but it will be committed soon). I fixed includes to compile in non-unity mode and without PCH. I didn't yet switch to 4.25 but I don't expect problems there.

With that, I'm closing the issue since the gist of it is solved. Comparing with your change, I don't see anything significant that would be missing. But feel free to reopen if you sync and still get compile warnings.

**Comment by jerryeds** [comment]
I'll give it a shot today. Thanks for the change! :)
