### ISSUE TITLE
[Linux] Compiling for Server Target fails (UE 4.25)

### ISSUE THREAD

**Issue by Markyparky56** [segross/UnrealImGui#36]
Related issue to https://github.com/segross/UnrealImGui/issues/34

Using the suggested fixes from the issue above (making constructors `= delete` and adding `struct` to lines 172 and 173 of ImGuiModule.h) leaves the following error when compiling a Linux Server:

```
1>  ...\Plugins\ImGui\Source\ImGui\Private\ImGuiDelegatesContainer.cpp(17,23): error : no member named 'GetDelegatesContainerHandle' in 'FImGuiModule'
1>                          SetParent(&Module->GetDelegatesContainerHandle());
1>                                     ~~~~~~  ^
1>  1 error generated.
```

`GetDelegatesContainerHandle()` is declared in ImGuiModule.h and is one of the functions to which the `struct` keyword was added, however when compiling for the Server target it is `#if`'d out because WITH_EDITOR is 0. 

I can't for the life of me find a way to make Unreal just not bother compiling the plugin when targeting a Linux Server (no UI, no need for ImGui). However, omitting it from the DependencyModuleNames in the Build.cs file nor Blacklisting the Server target in the .uplugin made any difference. 

I have managed to get it to compile by playing some Linker Error whack-a-mole. If you comment the `#if WITH_EDITOR` blocks in ImGuiImplementation.cpp (lines 20 & 43, and lines 59 and 69), ImGuiImplementation.h (lines 10 & 16), ImGuiModule.h (lines 168 & 174), and ImGuiModule.cpp (lines 167 & 182) so that their contents is always compiled it seems happy. I doubt this is a clean or safe solution, however, and I'm unsure of any potential knock on effects this might be causing.

**Comment by segross** [comment]
Oh, hi Mark. I haven't yet fixed the issue with input binding that you mentioned to me once. Believe it or not, but I was planning to do that this month (probably a full year later or so ;) but kind of busy with other stuff.

And thanks for bringing this issue. It is a genuine bug, probably not even Linux only. I'll fix it. That redirection was meant for editor only but I forget to wrap it in the WITH_EDITOR directives. At least I think that you only need it for the editor as you cannot hot-reload standalone... but you never know, maybe somebody will prove me wrong.
As a quick workaround with minimal effort, I'd suggest removing WITH_EDITOR from the relevant declarations and definitions in the ImGuiModule. I'll try to later setup a toolchain for 4.25 cross-compilation because there has been a few issues recently.

But when it comes to including a module, I'd assume that it should be possible to control that from the Build.cs. I definitely tried that with different build configurations, but I'm not sure whether it is possible to switch based on targets.

And on a side note, ImGui could be actually useful on servers but it would need a Remote ImGui, which I still couldn't find time to add.

**Comment by segross** [comment]
The error is fixed in the latest version.

Out of curiosity I will try later to remove module from dependencies and see what will happen.

**Comment by Markyparky56** [comment]
Build seems happy with the new changes, thanks for the quick turnaround! 

No sweat about the input binding thing (Only been 7 months ;)), pretty sure everyone has reached the point where it's unconscious muscle memory to toggle one of the settings to rebind it after a hot-reload. 

Regarding removing the module as a dependency, I was finding no matter what I changed or added it was still insisting on compiling module.imgui.cpp. Documentation regarding .build.cs files and .uplugin files is painfully sparse, so there may be a way to do it. I tried making its addition to the `PublicDependencyModuleNames` list condition on the Target Type, as well as trying `BlacklistTargets` which shows up in both `FModuleDescriptor` and `FPluginReferenceDescriptor` but I couldn't tell exactly where to put that particular entry in the .uplugin file.

**Comment by segross** [comment]
> No sweat about the input binding thing (Only been 7 months ;)), pretty sure everyone has reached the point where it's unconscious muscle memory to toggle one of the settings to rebind it after a hot-reload.

Not sure whether this is the same issue. I was thinking about the issue that the binding is only added to the the default object of the base class and active input objects at start... or something like that. What is the issue with the hot-reload?
