### ISSUE TITLE
Upgrading to Dear ImGui 1.60 

### ISSUE THREAD

**Issue by tstaples** [segross/UnrealImGui#9]
Hey, I was wondering if you had plans on updating this plugin to use ImGui 1.60 in the near future.

I was testing out the upgrade locally and it's pretty smooth, but the removal of the global default context causes some issues that would take me some time to solve. So if you were already in the process of doing it I'd rather wait.

There's also work needed to be done to allow for the keyboard/gamepad navigation changes to be used but personally I'm in no rush for it.

**Comment by segross** [comment]
Hey, I didn’t notice that there is a newer version. I’ve just checked and got it working but give me a few days to clean it. Removing the global default context and adding interface for shared font atlas made me actually quite happy as it should allow me to clean a workaround that I added at some point. However, I also want to revisit how I manage PIE and Editor contexts and I will need to see whether it is better to do it before or after this upgrade. I have a bit limited time for that project recently but I should be able to commit something in a next few days. Since there are some breaking changes in ImGui itself I suppose that I will run it trough experimental branch first.

Support for controller is also pretty cool, so I will definitely try it.

**Comment by segross** [comment]
Plugin is upgraded to ImGui 1.61 and keyboard/gamepad navigation is enabled as experimental feature.
